// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1z6uzKQJrhieQLKdWgNHB4nR3dIqKPMQ',
    appId: '1:927239353449:web:4f56eace2509938469def8',
    messagingSenderId: '927239353449',
    projectId: 'tibicledemo',
    authDomain: 'tibicledemo.firebaseapp.com',
    storageBucket: 'tibicledemo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJabJpTwY-AdBbfqCY_b7z58kqy-hw9gY',
    appId: '1:927239353449:android:813bc124c3c670a969def8',
    messagingSenderId: '927239353449',
    projectId: 'tibicledemo',
    storageBucket: 'tibicledemo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTNBaeXpvVrSL2rmChlQPUoJN9EYuk3sQ',
    appId: '1:927239353449:ios:00f9a7166df63dc969def8',
    messagingSenderId: '927239353449',
    projectId: 'tibicledemo',
    storageBucket: 'tibicledemo.firebasestorage.app',
    iosBundleId: 'com.example.tibicleOfflineDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTNBaeXpvVrSL2rmChlQPUoJN9EYuk3sQ',
    appId: '1:927239353449:ios:00f9a7166df63dc969def8',
    messagingSenderId: '927239353449',
    projectId: 'tibicledemo',
    storageBucket: 'tibicledemo.firebasestorage.app',
    iosBundleId: 'com.example.tibicleOfflineDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1z6uzKQJrhieQLKdWgNHB4nR3dIqKPMQ',
    appId: '1:927239353449:web:cf0d2b8a0b96891669def8',
    messagingSenderId: '927239353449',
    projectId: 'tibicledemo',
    authDomain: 'tibicledemo.firebaseapp.com',
    storageBucket: 'tibicledemo.firebasestorage.app',
  );
}
